Update patch.yml

diff --git a/.github/workflows/patch.yml b/.github/workflows/patch.yml
--- a/.github/workflows/patch.yml
+++ b/.github/workflows/patch.yml
@@ -20,7 +20,29 @@ jobs:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
+          
+      - name: Validate inputs
+        run: |
+          # check that the format is `YYMMDD.N`
+          if ! [[ "${{ github.event.inputs.build-number }}" =~ ^[[:digit:]]{6}.[[:digit:]]+$ ]]; then
+            echo "ERROR: `build-number` input has an incorrect format. Please check that the format is `YYMMDD.N`
+            exit 1
+          fi
 
+          # check that build branch exists
+          if ! [[ $(git rev-parse --verify --quiet origin/${{ github.event.inputs.build-number }}) ]]; then
+            echo "ERROR: Could not find branch `origin/${{ github.event.inputs.build-number }}`. Please check that it exists"
+            exit 1
+          fi
+
+          # check that the commits exist
+          read -r -a SHAS <<< "${{ github.event.inputs.shas }}"
+          for SHA in "${SHAS[@]}"; do
+            if ! [[ $(git branch --quiet --contains $SHA) ]]; then
+              echo "ERROR: Could not find commit ${SHA} on main. Please check that it exists"
+              exit 1
+            fi
+          done
       - name: Increment patch by one
         id: get-cp-build-number
         run: |
@@ -41,6 +63,6 @@ jobs:
           git config --global user.email $EMAIL
       - name: Cherry-pick ${{ github.event.inputs.build-number }} with ${{ github.event.inputs.shas }}
         run: |
-          git checkout -b ${{ steps.get-cp-build-number.outputs.cp-build-number }} origin/${{ github.event.inputs.build-number }}
+          git switch --create ${{ steps.get-cp-build-number.outputs.cp-build-number }} origin/${{ github.event.inputs.build-number }}
           git cherry-pick -x ${{ github.event.inputs.shas }}
           git push --set-upstream origin ${{ steps.get-cp-build-number.outputs.cp-build-number }}
